library(testthat)
source("src/bride_income_audit.R")
audit <- bride_income_audit()

test_that("the earnings regression has three verified unidentified directions", {
  expect_equal(nrow(audit$training_matrix), 83L)
  expect_equal(ncol(audit$training_matrix) - qr(audit$training_matrix)$rank, 3L)
  expect_equal(qr(audit$null_basis)$rank, 3L)
  expect_lt(max(abs(audit$training_matrix %*% audit$null_basis)), 1e-12)
  expect_equal(sum(!audit$support$supported_prediction), 115L)
  expect_equal(
    colSums(audit$prediction_matrix %*% audit$null_basis != 0),
    c(post_secondary = 16, other_field = 39, education_intercept = 80)
  )
  r_predictions <- predict(audit$first_stage,
    readRDS("output/limited_models.rds")$T4_1$data,
    rankdeficient = "non-estim"
  )
  expect_equal(unname(sort(attr(r_predictions, "non-estim"))), unname(which(!audit$support$supported_prediction)))
})

test_that("the reconstructed author predictions preserve every exported profile and income", {
  comparison <- audit$author_comparison
  expect_equal(sort(comparison$author_row), seq_len(3944L))
  expect_equal(sort(comparison$analysis_row), seq_len(3944L))
  expect_lt(max(abs(comparison$author_prediction - comparison$reconstructed_prediction)), 1e-6)
  covariate_error <- audit$counts$value[audit$counts$quantity == "author_export_maximum_covariate_difference"]
  expect_lt(covariate_error, 1e-7)
  expect_true(all(audit$published_comparison$matches_printed_precision))
  expect_equal(nrow(audit$published_comparison), 18L)
})

test_that("equal earnings fits yield different full-sample income slopes", {
  scenarios <- audit$normalizations
  expect_lt(diff(range(scenarios$earnings_weighted_sse)), 1e-10)
  expect_lt(max(scenarios$maximum_training_prediction_change), 1e-12)
  expect_gt(max(scenarios$predicted_income), .12)
  expect_lt(min(scenarios$predicted_income), 0)
  expect_lt(diff(range(scenarios$supported_predicted_income)), 1e-10)
  expect_lt(diff(range(scenarios$supported_same_caste)), 1e-10)
  support <- audit$support$supported_prediction
  expect_equal(audit$support$default_r_prediction[support], audit$support$author_prediction[support])
  expect_gt(max(abs(audit$support$default_r_prediction - audit$support$author_prediction)), 1)
})

test_that("saved results are regenerated by the complete audit", {
  for (name in c("counts", "normalizations", "published_comparison", "author_comparison", "support")) {
    saved <- read.csv(paste0("output/bride_income_", name, ".csv"))
    expected <- audit[[name]]
    rownames(expected) <- NULL
    expect_equal(saved, expected, tolerance = 1e-10)
  }
})
